stages:
  - setup
  - contrib
  - make

# image should match what is used for lb-docker-run (see build-env)
image: gitlab-registry.cern.ch/rmatev/lb-stack-setup/centos7-build:v4.57.py3

# setup as readme:
#   stage: setup
#   script:
#     - curl https://gitlab.cern.ch/rmatev/lb-stack-setup/raw/master/setup.py | python3 - -b $CI_COMMIT_SHA stack

setup:
  stage: setup
  tags:
    - cvmfs
  script:
    - git --version
    - python3 setup.py --debug --repo $CI_REPOSITORY_URL --branch $CI_COMMIT_SHA stack
    - cd stack
    - utils/config.py useDistcc false
    # python3 setup.py --repo . [--branch $CI_COMMIT_SHA] stack
  artifacts:
    paths:
      - stack/

contrib:
  stage: contrib
  tags:
    - cvmfs
  variables:
    GIT_STRATEGY: none
  script:
    - cd stack
    - make contrib
    - bash utils/ci-utils/test-contrib.sh
  artifacts:
    paths:
      - stack/contrib/
    expire_in: 1 week

make:
  stage: make
  tags:
    - cvmfs
  variables:
    GIT_STRATEGY: none
  script:
    - cd stack
    - make Gaudi
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - stack/.ccache/

check-formatting:
  stage: setup
  image: gitlab-registry.cern.ch/lhcb-docker/style-checker
  script:
    - curl -o lb-format "https://gitlab.cern.ch/lhcb-core/LbDevTools/raw/master/LbDevTools/SourceTools.py?inline=false"
    - python lb-format --format-patch apply-formatting.patch origin/master
  artifacts:
    paths:
      - apply-formatting.patch
    when: on_failure
    expire_in: 1 week
