#!/bin/bash
set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$DIR/helpers.sh"
logname="build-env"

BINARY_TAG="$( "$DIR/config.py" binaryTag )"
USE_DOCKER="$( "$DIR/config.py" useDocker )"

if [ "$USE_DOCKER" != true ]; then
    HOST_OS=$(/cvmfs/lhcb.cern.ch/lib/bin/host_os)
    if [ "$HOST_OS" != x86_64-centos7 ]; then
        log ERROR "Host OS $HOST_OS is not supported. Find a CentOS 7 machine"
        log ERROR "or use docker by setting \"useDocker\" to true in ${DIR}/config.json"
        exit 1
    fi
else
    # TODO make kerberos optional?
    export KRB5CCNAME=$(klist 2>/dev/null | head -1 | grep -o 'FILE:.*')
    if [ -z "$KRB5CCNAME" ]; then
        log ERROR "No kerberos ticket cache of the form 'FILE:path/to/file' was found."
        log ERROR "Please do this to forward a kerberos ticket to the conainer:"
        log ERROR
        log ERROR "    export KRB5CCNAME='FILE:/tmp/krb5cc_$(id -u)'; kinit <username>@CERN.CH"
        log ERROR
        exit 1
    fi
    # TODO is there a way to forward cache from types other than FILE, e.g KCM?
fi

# Check for a valid ticket
if ! klist -s; then
    log ERROR "No valid ticket found. Please get a new one with"
    log ERROR
    log ERROR "    kinit <username>@CERN.CH"
    log ERROR
    exit 1
fi

if [ "$USE_DOCKER" = true ]; then
    "${DIR}/lb-docker-run" \
        --docker-tag v4.57 \
        --quiet-env --lbenv -c ${BINARY_TAG} \
        -C "${DIR}/.." --use-absolute-path --kerberos \
        ${LB_DOCKER_RUN_FLAGS} \
        "$@"
else
    # TODO start a clean LbEnv a la lb-docker-run
    #      eg /cvmfs/lhcb.cern.ch/lib/LbEnv -c ${BINARY_TAG} ...
    export BINARY_TAG
    export CMTCONFIG="${BINARY_TAG}"
    "$@"
fi
