#!/bin/bash
set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
BINARY_TAG="$( git config --file "${DIR}/config" platform.binaryTag )"

# Find the project, i.e. the first option not starting with a dash
for iproject in $(seq 1 $#); do
    if [[ "${!iproject}" != -* ]]; then
        break
    fi
done

PROJECT="${!iproject}"
export LB_DOCKER_RUN_FLAGS="--ptrace ${@:1:$iproject-1}"
"${DIR}/build-env" ${PROJECT}/build.${BINARY_TAG}/run "${@:$iproject+1}"
