#!/bin/bash
set -eo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$DIR/helpers.sh"
logname="build-env"
eval $(config --sh outputPath binaryTag buildPath contribPath)

stats_dir="$outputPath/stats/$binaryTag"
reference="$stats_dir/start.timestamp"
echo "Statistics for build started on $(date -r $reference)"
echo

# merge stats from all projects
export CCACHE_STATSLOG=$stats_dir/ccache-statslog
find $stats_dir -maxdepth 1 -name '*.ccache-statslog' -type f -newer $reference \
  | xargs -r cat > $stats_dir/ccache-statslog
echo "=============== ccache stats ==============="
$contribPath/bin/ccache --show-log-stats -v | grep -v ' 0$'
echo

echo "=============== ninja stats ================"
find "$buildPath"/*/build.$binaryTag -maxdepth 1 -name '.ninja_log' -type f -newer $reference \
  | xargs -r $DIR/external/post_build_ninja_summary.py
